# Generated by Django 4.2.4 on 2023-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_publicmessage_delete_publicmessege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='messageText',
            field=models.TextField(default='messageText'),
            preserve_default=False,
        ),
    ]
